repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: git://github.com/doublify/pre-commit-isort
    rev: v4.3.0
    hooks:
    -   id: isort
-   repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
    -   id: black
# -   repo: https://gitlab.com/PyCQA/flake8
#     rev: 3.8.4
#     hooks:
#     -   id: flake8
-   repo: https://github.com/life4/flakehell
    rev: v.0.8.0
    hooks:
    -   id: flakehell
